* Building on macOS
    :PROPERTIES:
    :CUSTOM_ID: building-on-macos
    :END:

  This is a fork of https://github.com/klayoutmatthias/klayout. The
  purpose is to provide a stable build on recent macOS, supported by
  homebrew. There are three complications to this goal:

  - Toolkit: local/qt5 - Homebrew doesn't provide Qt4, only Qt5 and built
    with clang. The default (black) background makes graphics except the
    grid invisible. Workaround: select another background

  - Compiler: local/clang - Apple/LLVM clang++ seems to work differently
    from GNU/GCC g++.

    std::iterator\_traits requires /all/ five typedefs are consistently
    defined.

    Different treatment of template instantiation in convenience libraries
    (weak symbols) causes eg singletons to be duplicated. Workaround: use
    -fvisibility=default

  - Application bundle: local/build - Qt5 macdeployqt doesn't quite cut
    it.

    Some Qt-frameworks /inside/ the bundle still points to other
    Qt-frameworks /outside/ the bundle. Workaround: run final fixup of
    references, see bundle.sh
    
  Workflow:
  #+BEGIN_SRC sh
    cd /opt/klayout/git
    sh ./build.sh \
       -pylib /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6m.dylib \
       -pyinc /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/include/python3.6m \
       -debug -j4 install \
       1>build-debug.log 2>build-debug.err
    cd ../bin-debug
    sh ../bundle.sh klayout.app
  #+END_SRC


* klayout
  :PROPERTIES:
  :CUSTOM_ID: klayout
  :END:

This repository will hold the main sources for the KLayout project.

Plugins can be included into the "plugins" directory from external
sources.

For more details see http://www.klayout.org.

** Building requirements
   :PROPERTIES:
   :CUSTOM_ID: building-requirements
   :END:

- Qt 4.8 or later (4.6 with some restrictions)
- gcc 4.x or later

Here is a list of packages required for various Linux flavors:

- CentOS (6, 7): gcc gcc-c++ make qt qt-devel ruby ruby-devel python
  python-devel
- OpenSuSE: (13.2, 41.1): gcc gcc-c++ make libqt4 libqt4-devel ruby
  ruby-devel python3 python3-devel
- Ubuntu (14.04, 16.10): gcc g++ make libz-dev libqt4-dev-bin libqt4-dev
  ruby ruby-dev python3 python3-dev

** Build options
   :PROPERTIES:
   :CUSTOM_ID: build-options
   :END:

- Ruby: with this option, Ruby scripts can be executed and developped
  within KLayout. Ruby support is detected automatically by the build
  script.
- Python: with this option, Python scripts can be executed and
  developped within KLayout. Python support is detected automatically by
  the build script.
- Qt binding: with this option, Qt objects are made available to Ruby
  and Python scripts. Qt bindings are enabled by default. Qt binding
  offers an option to create custom user interfaces from scripts and to
  interact with KLayout's main GUI. On the other hand, they provide a
  considerable overhead when building and running the application.
- 64 bit coordinate support: with this option, the coordinate type used
  internally is extended to 64bit as compared to 32bit in the standard
  version. This will duplicate memory requirements for coordinate lists,
  but allow a larger design space. 64bit coordinate support is
  experimental and disabled by default.

** Building instructions (Linux)
   :PROPERTIES:
   :CUSTOM_ID: building-instructions-linux
   :END:

*** Plain building for Qt4
    :PROPERTIES:
    :CUSTOM_ID: plain-building-for-qt4
    :END:

#+BEGIN_EXAMPLE
    ./build.sh 
#+END_EXAMPLE

*** Plain building for Qt5
    :PROPERTIES:
    :CUSTOM_ID: plain-building-for-qt5
    :END:

#+BEGIN_EXAMPLE
    ./build.sh -qt5 
#+END_EXAMPLE

*** Building without Qt binding
    :PROPERTIES:
    :CUSTOM_ID: building-without-qt-binding
    :END:

#+BEGIN_EXAMPLE
    ./build.sh -without-qtbinding
#+END_EXAMPLE

*** Debug build
    :PROPERTIES:
    :CUSTOM_ID: debug-build
    :END:

#+BEGIN_EXAMPLE
    ./build.sh -debug
#+END_EXAMPLE

*** Building with a particular Ruby version
    :PROPERTIES:
    :CUSTOM_ID: building-with-a-particular-ruby-version
    :END:

#+BEGIN_EXAMPLE
    ./build.sh -ruby <path-to-ruby>
#+END_EXAMPLE

(path-to-ruby is the full path of the particular ruby interpreter)

*** Building with a particular Python version
    :PROPERTIES:
    :CUSTOM_ID: building-with-a-particular-python-version
    :END:

#+BEGIN_EXAMPLE
    ./build.sh -python <path-to-python>
#+END_EXAMPLE

(path-to-python is the full path of the particular python interpreter)

*** Building with a particular Qt version
    :PROPERTIES:
    :CUSTOM_ID: building-with-a-particular-qt-version
    :END:

#+BEGIN_EXAMPLE
    ./build.sh -qmake <path-to-qmake>
#+END_EXAMPLE

(path-to-qmake is the full path of the particular qmake installation)

*** Building with 64bit coordinate support (experimental)
    :PROPERTIES:
    :CUSTOM_ID: building-with-64bit-coordinate-support-experimental
    :END:

#+BEGIN_EXAMPLE
    ./build.sh -with-64bit-coord
#+END_EXAMPLE

*** Pass make options
    :PROPERTIES:
    :CUSTOM_ID: pass-make-options
    :END:

#+BEGIN_EXAMPLE
    ./build.sh -j4 
#+END_EXAMPLE

(for running 4 jobs in parallel)

*** More options
    :PROPERTIES:
    :CUSTOM_ID: more-options
    :END:

For more options use

#+BEGIN_EXAMPLE
    ./build.sh -h
#+END_EXAMPLE

** Running the Test Suite (Linux)
   :PROPERTIES:
   :CUSTOM_ID: running-the-test-suite-linux
   :END:

Go to the build directory (i.e. "bin-release") and enter

#+BEGIN_EXAMPLE
    export TESTTMP=testtmp    # path to a directory that will hold temporary data (will be created)
    export TESTSRC=..         # path to the source directory
    ./ut_runner
#+END_EXAMPLE

For more options use

#+BEGIN_EXAMPLE
    ./ut_runner -h
#+END_EXAMPLE
